### PR TITLE
added customisation option for fzf prompt

### PR DESCRIPTION
**Pull request by gennaro-tedesco**
- add customisation option for fzf prompt string
- address discussion as per [here](https://github.com/gennaro-tedesco/nvim-possession/pull/30#issuecomment-1714539197)

https://github.com/gennaro-tedesco/nvim-possession/assets/15387611/bbcbbcf0-8af4-4425-89ca-99ffcaf8dd7a

### CODE REVIEW

**Comment by gennaro-tedesco** [comment]
@MariaSolOs please have a look at this PR and see if this is the intended behaviour (the screenshot above shows the look).

**Comment by MariaSolOs** [comment]
@gennaro-tedesco why not just combine the `session_icon` and `session_prompt` settings into a single one? Given that the icon is only used in the prompt, users can just add the icon there :)

**Comment by gennaro-tedesco** [comment]
> Given that the icon is only used in the prompt, users can just add the icon there :)

The icon is also used in the statusline, see [here](https://github.com/gennaro-tedesco/nvim-possession/blob/3ee113784e69c3d39ac1e1e2037497b12c12188b/lua/nvim-possession/init.lua#L26), where you would have the pair (icon, session name) whereas in the prompt you have the pair (icon, session prompt).

**Comment by MariaSolOs** [comment]
@gennaro-tedesco got it. Then this looks good to me!

**Comment by gennaro-tedesco** [comment]
Merged: the new customisation option is available in [v0.0.13](https://github.com/gennaro-tedesco/nvim-possession/releases/tag/v0.0.13): updating the plugin will do.

**Comment by MariaSolOs** [comment]
@gennaro-tedesco that's great, thanks a lot!

**Pull request merged**
